# Site settings
title: Pranjal Bhatnagar
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pranjal Bhatnagar
user_description: I\'m a DevOps Engineer, always searching for the next challenge; no task is too scary nor too difficult.
user_title: DevOps Engineer
email: pranjal091994@live.com
# twitter_username: lorem_ipsum
github_username:  pranjal7
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
